name: YaQinKingのメモ帳
description: 最爱二次元Loli 正在努力成为 Mac 软件开发者中
meta_description: "YaQinKingのメモ帳"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'https://yaqink.github.io'
google_analytics: 'UA-60494668-1'

# Details for the RSS feed generator
url:            'https://yaqink.github.io'
author:         'YaQinKing'
