name: YaQinKingのメモ帳
description: 最爱二次元Loli 正在努力成为 Mac 软件开发者中
meta_description: "YaQinKingのメモ帳"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'https://yaqink.github.io'
google_analytics: 'UA-60494668-1'

# Markdown render redcarpet options
redcarpet:
  extensions: ["hard_wrap", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "superscript"]

# Details for the RSS feed generator
url:            'https://yaqink.github.io'
author:         'YaQinKing'
